const { Trail } = require('../models');

const trailData = [
  {
    trail_name: 'Hebron Falls',
    distance: 3.5,
    difficulty: "easy",
    dog_friendly: true ,
    elevation_gain: 216 ,
    type: "out & back",
    location_id: 1,
    approved: true,
  },
  {
    trail_name: 'Greenway Trail Loop',
    distance: 3.1 ,
    difficulty: 'easy',
    dog_friendly: true,
    elevation_gain: 183,
    type: 'loop',
    location_id: 1,
    approved: true,
  },
  {
    trail_name: 'Rocky Knob Trail',
    distance: 7.3,
    difficulty:'moderate',
    dog_friendly: false,
    elevation_gain: 905,
    type: 'loop',
    location_id:1 ,
    approved: true,
  },
  {
    trail_name: 'Craven Gap to Lane Pinnacle',
    distance:12.7 ,
    difficulty:'hard',
    dog_friendly: true,
    elevation_gain: 3182,
    type: 'out & back',
    location_id: 2,
    approved: true,
  },
  {
    trail_name: 'Richmond Hill Park Trail',
    distance: 2.8,
    difficulty:'easy',
    dog_friendly: true,
    elevation_gain: 272,
    type: 'loop',
    location_id: 2,
    approved: true,
  },
  {
    trail_name: 'Hard Times Road Trail',
    distance: 7.9,
    difficulty:'moderate',
    dog_friendly: true,
    elevation_gain: 928,
    type: 'out & back',
    location_id: 2,
    approved: true,
  },
  {
    trail_name: 'Deep Creek Trail',
    distance: 4.9,
    difficulty:'moderate',
    dog_friendly: false,
    elevation_gain: 895,
    type: 'loop',
    location_id: 3,
    approved: true,
  },
  {
    trail_name: 'Lonesome Pine Overlook',
    distance: 6.6,
    difficulty:'hard',
    dog_friendly: false,
    elevation_gain: 2273,
    type: 'out & back',
    location_id: 3,
    approved: true,
  },
  {
    trail_name: 'Goldmine Loop Trail',
    distance: 3,
    difficulty:'moderate',
    dog_friendly: false,
    elevation_gain: 780,
    type: 'loop',
    location_id: 3,
    approved: true,
  },
  {
    trail_name: 'Looking Glass Rock Trail',
    distance: 5.8,
    difficulty:'moderate',
    dog_friendly: true,
    elevation_gain: 1722,
    type: 'out & back',
    location_id: 4,
    approved: true,
  },
  {
    trail_name: 'Pink Beds Trail',
    distance: 6,
    difficulty:'easy',
    dog_friendly: true,
    elevation_gain: 337,
    type: 'loop',
    location_id: 4,
    approved: true,
  },
  {
    trail_name: 'Twin Falls Trail',
    distance: 7.2,
    difficulty:'moderate',
    dog_friendly: true,
    elevation_gain: 1099,
    type: 'loop',
    location_id: 4,
    approved: true,
  },
  {
    trail_name: 'Triple Falls Trail',
    distance: 2.9,
    difficulty:'easy',
    dog_friendly: true,
    elevation_gain: 439,
    type: 'loop',
    location_id: 5,
    approved: true,
  },
  {
    trail_name: 'Stone Mountain Summit Trail',
    distance: 3.2,
    difficulty:'moderate',
    dog_friendly: true,
    elevation_gain: 693,
    type: 'out & back',
    location_id: 5,
    approved: true,
  },
  {
    trail_name: 'Oklawaha Greenway',
    distance: 6.9,
    difficulty:'easy',
    dog_friendly: true,
    elevation_gain: 170,
    type:'out & back' ,
    location_id: 5,
    approved: true,
  },
  {
    trail_name: 'The Pinnacle Trail',
    distance: 7.4,
    difficulty: 'hard',
    dog_friendly: true,
    elevation_gain: 2477,
    type: 'loop',
    location_id: 6,
    approved: true,
  },
  {
    trail_name: 'Blackrock Mountain Trail',
    distance: 4.8,
    difficulty:'hard',
    dog_friendly: true,
    elevation_gain: 1433,
    type:'out & back' ,
    location_id: 6,
    approved: true,
  },
  {
    trail_name: 'Yellow Face Trail',
    distance: 1.6,
    difficulty:'moderate',
    dog_friendly: true,
    elevation_gain: 492,
    type: 'out & back',
    location_id: 6,
    approved: true,
  },
  {
    trail_name: 'Elk Knob Summit',
    distance: 3.8,
    difficulty:'moderate',
    dog_friendly: true,
    elevation_gain: 961,
    type: 'out & back',
    location_id: 7,
    approved: true,
  },
  {
    trail_name: 'Nuwati Trail',
    distance: 3 ,
    difficulty:'moderate',
    dog_friendly: true,
    elevation_gain: 551,
    type: 'out & back',
    location_id: 7,
    approved: true,
  },
  {
    trail_name: 'Lower Pond Creek Trail',
    distance: 1.4,
    difficulty:'hard',
    dog_friendly:false,
    elevation_gain: 446,
    type: 'out & back',
    location_id: 7,
    approved: true,
  },


];

const seedTrails = () => Trail.bulkCreate(trailData);

module.exports = seedTrails;